spring:
  datasource:
    druid:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://cdb-lx88tlpe.bj.tencentcdb.com:10264/peter?autoReconnect=true&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: Ch@ng010103
  mvc:
    view:
      suffix: .html
    static-path-pattern: /**
  resources:
    static-locations: classpath:/templates/,classpath:/static/
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
    freemarker:
      cache: false    #页面不加载缓存，修改即时生效
mybatis-plus:
  type-aliases-package: com.peter.xiao.main.entity
  mapper-locations: classpath:/com/peter/xiao/main/mapper/xml/*.xml

err:
  file: err.log
  head: logs
configParam:
  salt: 8
server:
  port: 8003
