spring:
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: true #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候会抛出异常,不启动则使用默认数据源.
      datasource:
        master:
          url: jdbc:mysql://cdb-lx88tlpe.bj.tencentcdb.com:10264/peter?autoReconnect=true&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull
          username: root
          password: Ch@ng2001
          driver-class-name: com.mysql.jdbc.Driver
        sub:
          url: jdbc:mysql://rm-8vb661b58so33mt83ho.mysql.zhangbei.rds.aliyuncs.com:3306/b2c_a_test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=true&useAffectedRows=true&serverTimezone=GMT%2B8
          username: b2c_a
          password: b2c_a123456
          driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      suffix: .html
    static-path-pattern: /**
  resources:
    static-locations: classpath:/templates/,classpath:/static/
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
    freemarker:
      cache: false    #页面不加载缓存，修改即时生效
mybatis-plus:
  type-aliases-package: com.peter.xiao.main.entity
  mapper-locations: classpath:/com/peter/xiao/main/mapper/xml/*.xml

err:
  file: err.log
  head: logs
configParam:
  salt: 8
server:
  port: 8003
